version: '3.9'

services:
  php:
    container_name: Slim_php
    image: php:8.0.1-alpine3.12
    working_dir: /slim
    command: php -S 0.0.0.0:8000 -t public
    environment:
      docker: 'true'
    volumes:
    - .:/slim
    ports:
    - 8000:8000
    networks:
      - bridge

  composer:
    container_name: composer
    image: composer:2.0.8
    user: 1000:1000 #change this if your user isn't on 1000
    working_dir: /slim
    command: composer install --ignore-platform-reqs
    volumes:
    - .:/slim
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
